
-- Script de migración generado automáticamente
-- ALTER TABLE global_subjects ADD COLUMN IF NOT EXISTS layout_row INTEGER DEFAULT 0;

BEGIN;
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-info1';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-teccomp';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-algegeo';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-am1a';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-fis1';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-info2';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-algelin';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-quimica';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-am1b';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-fis2';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-ingweb1';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-ingsoft1';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-bd1';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-am2a';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-estdisc';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-info3';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-arqcomp1';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-am2b';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-metnum';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-probest';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-arqcomp2';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-fis3';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-pds1';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-sisop';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-teocomp';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-audit';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-derecho';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-orgemp';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-pds2';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-redes1';
UPDATE global_subjects SET layout_row = 5 WHERE code = 'cs-dhs';
UPDATE global_subjects SET layout_row = 6 WHERE code = 'cs-ingles';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-ingweb2';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-bd2';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-ingsoft2';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-redes2';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-economia';
UPDATE global_subjects SET layout_row = 5 WHERE code = 'cs-progfunc';
UPDATE global_subjects SET layout_row = 6 WHERE code = 'cs-tecmov';
UPDATE global_subjects SET layout_row = 7 WHERE code = 'cs-linux';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-gestemp1';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-gestproy';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-modsim';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-redes3';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-ingweb3';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-compgraf';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-gestemp2';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-sisrt';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-audit2';
UPDATE global_subjects SET layout_row = 0 WHERE code = 'cs-planneg';
UPDATE global_subjects SET layout_row = 1 WHERE code = 'cs-seginf';
UPDATE global_subjects SET layout_row = 2 WHERE code = 'cs-tfg';
UPDATE global_subjects SET layout_row = 3 WHERE code = 'cs-pps';
UPDATE global_subjects SET layout_row = 4 WHERE code = 'cs-ia';
COMMIT;
