export interface EquivalencyRule {
  targetSubject: string; // Materia del Plan 2026/2025
  requiredSubjects: string[]; // Materias del Plan 2016
  partial?: boolean;
}

export const EQUIVALENCIES: EquivalencyRule[] = [
  { targetSubject: 'Análisis Matemático I', requiredSubjects: ['Análisis Matemático 1A', 'Análisis Matemático 1B'] },
  { targetSubject: 'Álgebra y Geometría Analítica', requiredSubjects: ['Álgebra y Geometría', 'Álgebra Lineal'] },
  { targetSubject: 'Física I', requiredSubjects: ['Física 1'] },
  { targetSubject: 'Paradigmas de Programación I', requiredSubjects: ['Informática 1', 'Informática 2'] },
  { targetSubject: 'Tecnología de Computadoras', requiredSubjects: ['Tecnología de Computadoras'] },
  { targetSubject: 'Organización Empresarial e Industrial', requiredSubjects: ['Gestión de Empresas 1'] },
  { targetSubject: 'Técnicas de Desarrollo', requiredSubjects: ['Informática 1'] },
  { targetSubject: 'Sistemas de Información', requiredSubjects: ['Informática 1', 'Tecnología de Computadoras'] },
  { targetSubject: 'Estructuras de Datos y Algoritmos', requiredSubjects: ['Informática 3'] },
  { targetSubject: 'Análisis Matemático II', requiredSubjects: ['Análisis Matemático 2A', 'Análisis Matemático 2B'] },
  { targetSubject: 'Física II', requiredSubjects: ['Física 2'] },
  { targetSubject: 'Matemática Discreta', requiredSubjects: ['Estructuras Discretas'] },
  { targetSubject: 'Paradigmas de Programación II', requiredSubjects: ['Ingeniería Web 1'] },
  { targetSubject: 'Arquitectura de Computadoras', requiredSubjects: ['Arquitectura de Comp. 1'] },
  { targetSubject: 'Bases de Datos I', requiredSubjects: ['Base de Datos 1'] },
  { targetSubject: 'Probabilidad y Estadística', requiredSubjects: ['Probabilidad y Estadística'] },
  { targetSubject: 'Física III', requiredSubjects: ['Física 2', 'Física 3'] },
  { targetSubject: 'Ingeniería de Requerimientos', requiredSubjects: ['Ingeniería de Software 1'] },
  { targetSubject: 'Taller de Integración I', requiredSubjects: ['Ingeniería de Software 1'] },
  { targetSubject: 'Sistemas de Comunicaciones', requiredSubjects: ['Redes 1'] },
  { targetSubject: 'Procesos de Software I', requiredSubjects: ['Proceso de Desarrollo de Software 1'] },
  { targetSubject: 'Teoría de la Computación', requiredSubjects: ['Teoría de la Computación'] },
  { targetSubject: 'Sistemas Operativos', requiredSubjects: ['Sistemas Operativos'] },
  { targetSubject: 'Paradigmas de Programación III', requiredSubjects: ['Prog. Funcional y Scripting'] },
  { targetSubject: 'Análisis y Cálculo Numérico', requiredSubjects: ['Métodos Numéricos'] },
  { targetSubject: 'Desarrollo Web Seguro', requiredSubjects: ['Ingeniería Web 2'] },
  { targetSubject: 'Procesos de Software II', requiredSubjects: ['Proceso de Desarrollo de Software 2'] },
  { targetSubject: 'Bases de Datos II', requiredSubjects: ['Base de Datos 2'] },
  { targetSubject: 'Taller de Integración II', requiredSubjects: ['Proceso de Desarrollo de Software 2', 'Ingeniería Web 2'] },
  { targetSubject: 'Electiva I - IUA: Desarrollo de Herramientas de Software', requiredSubjects: ['Desarrollo de Herramientas de Software'] },
  { targetSubject: 'Taller de Integración III', requiredSubjects: ['Arquitectura Orientada a Servicios'] },
  { targetSubject: 'Identificación, Formulación, Evaluación y Gestión de Proyectos de Ingeniería', requiredSubjects: ['Gestión de Empresas 2', 'Plan de Negocios'] },
  { targetSubject: 'Modelos y Simulación', requiredSubjects: ['Modelos y Simulación'] },
  { targetSubject: 'Ingeniería Web', requiredSubjects: ['Ingeniería Web 3'] },
  { targetSubject: 'Desarrollo de Aplicaciones Móviles', requiredSubjects: ['Tecnologías Móviles'] },
  { targetSubject: 'Legislación para Ingeniería', requiredSubjects: ['Derecho y Ética Profesional'] },
  { targetSubject: 'Gestión de Proyectos TIC', requiredSubjects: ['Gestión de Proyectos Informáticos'] },
  { targetSubject: 'Electiva II – IUA: Redes de transmisión de datos', requiredSubjects: ['Redes 2', 'Redes 3'] },
  { targetSubject: 'Electiva III - IUA: Blockchain y Contratos Inteligentes', requiredSubjects: ['Blockchain y Contratos Inteligentes'] },
  { targetSubject: 'Electiva IV - IUA: Computación Gráfica', requiredSubjects: ['Computación Gráfica y Ambientes Virtuales'] },
  { targetSubject: 'Electiva V - IUA: Sistemas Embebidos', requiredSubjects: ['Arquitectura de Comp. 2 (Parcial)'], partial: true },
  { targetSubject: 'Inteligencia Artificial', requiredSubjects: ['Inteligencia Artificial'] },
  { targetSubject: 'Economía para Ingeniería', requiredSubjects: ['Economía'] },
  { targetSubject: 'Seguridad Informática', requiredSubjects: ['Seguridad Informática'] },
  { targetSubject: 'Calidad del Software', requiredSubjects: ['Ingeniería de Software 2'] },
  { targetSubject: 'Auditoría e Informática Forense', requiredSubjects: ['Auditoría'] },
  { targetSubject: 'Electiva VI - IUA: Sistemas en Tiempo Real', requiredSubjects: ['Sistemas en Tiempo Real'] },
  { targetSubject: 'Electiva VII - IUA: Pruebas de Sistemas Informáticos', requiredSubjects: ['Ingeniería de Software 2'], partial: true },
  { targetSubject: 'Práctica Profesional Supervisada', requiredSubjects: ['Práctica Profesional Supervisada'] },
  { targetSubject: 'Nivel de Idioma Inglés', requiredSubjects: ['Nivel Idioma Inglés'] },
];

export const PLAN_2026_CORRELATIVES: Record<string, string[]> = {
  'Electiva V - IUA: Sistemas Embebidos': ['Sistemas de Comunicaciones', 'Arquitectura de Computadoras'],
  'Economía para Ingeniería': ['Identificación, Formulación, Evaluación y Gestión de Proyectos de Ingeniería'],
  'Arquitectura de Computadoras': ['Tecnología de Computadoras'],
};
